"""Evidence source type — the canonical set of data source identifiers."""

from __future__ import annotations

from typing import Literal

EvidenceSource = Literal[
    "storage",
    "batch",
    "tracer_web",
    "cloudwatch",
    "aws_sdk",
    "knowledge",
    "grafana",
    "dagster",
    "datadog",
    "groundcover",
    "honeycomb",
    "coralogix",
    "eks",
    "github",
    "sentry",
    "mongodb",
    "postgresql",
    "mongodb_atlas",
    "mariadb",
    "kafka",
    "clickhouse",
    "azure_sql",
    "google_docs",
    "vercel",
    "opsgenie",
    "incident_io",
    "pagerduty",
    "jira",
    "elasticsearch",
    "prefect",
    "gitlab",
    "jenkins",
    "bitbucket",
    "openclaw",
    "posthog_mcp",
    "sentry_mcp",
    "x_mcp",
    "mysql",
    "rabbitmq",
    "betterstack",
    "snowflake",
    "azure",
    "openobserve",
    "opensearch",
    "alertmanager",
    "signoz",
    "tempo",
    "splunk",
    "supabase",
    "airflow",
    "argocd",
    "helm",
    "victoria_logs",
    "rds",
    "cloudtrail",
    "ec2",
    "hermes",
    "slack",
    "twilio",
    "telegram",
    "redis",
    "temporal",
    "interactive_shell",
]
